# Generated by Django 5.2 on 2025-04-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Indentificacion', models.CharField(max_length=11, unique=True, verbose_name='identificacion')),
                ('fecha_ingreso', models.DateTimeField(auto_now=True, verbose_name='Fecha Ingreso')),
                ('edad', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Salario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
    ]
